version: "3.7"
services:
  flask-server:
    build: ./flask-server
    networks:
      - demo
    ports:
      - "0.0.0.0:8080:8080" # Flask server port
    depends_on:
      - mysql
      - jaeger
    stop_grace_period: 1s
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    networks:
      - demo
    ports:
      - "0.0.0.0:5775:5775"
      - "0.0.0.0:6831:6831/udp"
      - "0.0.0.0:6832:6832"
      - "0.0.0.0:5778:5778"
      - "0.0.0.0:16686:16686"
      - "0.0.0.0:14268:14268"
      - "0.0.0.0:14250:14250"
      - "0.0.0.0:9411:9411"
  mysql:
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: wfh
      networks:
          - demo
      stop_grace_period: 1s

networks:
  demo: